# Generated by Django 5.0.2 on 2024-03-04 19:24

import django.db.models.deletion
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("price", models.PositiveIntegerField()),
                ("ingredients", models.TextField(blank=True, max_length=400)),
                (
                    "cuisine",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Italian"),
                            (2, "Japan"),
                            (3, "Chinese"),
                            (4, "Korean"),
                            (5, "Russian"),
                            (6, "Kazakh"),
                            (7, "Georgian"),
                            (8, "Turkish"),
                            (9, "Mexican"),
                            (10, "Uzbek"),
                            (11, "Thai"),
                            (12, "Indian"),
                            (13, "American"),
                            (14, "Caucasian"),
                        ],
                        default=6,
                    ),
                ),
                (
                    "taste",
                    models.PositiveIntegerField(
                        choices=[(1, "Spicy"), (2, "Salty"), (3, "Sweet"), (4, "Sour")],
                        default=1,
                    ),
                ),
                (
                    "photo",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True, null=True, upload_to="foods/"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Favorites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="foods.food"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
