# Generated by Django 5.0.2 on 2024-03-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="grade",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
