# Generated by Django 5.0.2 on 2024-03-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0002_food_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="grade",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
    ]
