# Generated by Django 5.0.2 on 2024-03-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "chef"), (2, "customer")], default=1
            ),
        ),
    ]
