# Generated by Django 5.0.2 on 2024-03-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_user", "0002_alter_role_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="username",
            new_name="middle_name",
        ),
        migrations.RemoveField(
            model_name="role",
            name="role",
        ),
        migrations.AddField(
            model_name="role",
            name="role_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "no_role"), (1, "chef"), (2, "customer")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="grade",
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
