# Generated by Django 5.0.2 on 2024-03-03 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "auth_user",
            "0003_rename_username_user_middle_name_remove_role_role_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PinToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(blank=True, max_length=4)),
                ("token", models.CharField(blank=True, max_length=32)),
                ("expiration", models.DateTimeField(blank=True, editable=False)),
                ("is_accepted", models.BooleanField(default=False)),
                ("is_expired", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pin_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Код для восстановления пароля",
                "verbose_name_plural": "Коды для восстановления пароля",
                "ordering": ["-created_at"],
                "unique_together": {("code", "is_accepted")},
            },
        ),
    ]
