# Generated by Django 5.0.2 on 2024-03-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_user", "0004_pintoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about_yourself",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="user",
            name="grade",
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
