# Generated by Django 5.0.2 on 2024-03-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_user", "0005_user_about_yourself_user_address_user_grade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="grade",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
    ]
