# Generated by Django 5.0.2 on 2024-03-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_user", "0007_user_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
